#!/bin/sh
# The E2E test need to pass before user can push to origin

$HOME/miniconda3/bin/robot e2e-test/substrate/substrate.robot
$HOME/miniconda3/bin/robot e2e-test/solana/solana.robot
$HOME/miniconda3/bin/robot e2e-test/health-check/health-check.robot || true
