// Generated by diesel_ext
#![allow(unused)]
#![allow(clippy::all)]

use super::schema::indexer_deployments;
use crate::deployment::IndexerHealth;
use massbit_data::indexer::DeploymentId;
use massbit_data::store::scalar::BigDecimal;
use serde_derive::Serialize;

type Bytes = Vec<u8>;

#[derive(Queryable, QueryableByName)]
#[table_name = "indexer_deployments"]
// We map all fields to make loading `Detail` with diesel easier, but we
// don't need all the fields
#[allow(dead_code)]
pub struct Deployment {
    pub id: DeploymentId,
    pub hash: String,
    pub namespace: String,
    pub schema: String,
    pub failed: bool,
    health: IndexerHealth,
    pub synced: bool,
    fatal_error: Option<String>,
    non_fatal_errors: Vec<String>,
    earliest_block_hash: Option<Bytes>,
    earliest_block_number: Option<BigDecimal>,
    pub latest_block_hash: Option<Bytes>,
    pub latest_block_number: Option<BigDecimal>,
    last_healthy_block_hash: Option<Bytes>,
    last_healthy_block_number: Option<BigDecimal>,
    pub entity_count: BigDecimal,
    graft_base: Option<String>,
    graft_block_hash: Option<Bytes>,
    graft_block_number: Option<BigDecimal>,
    reorg_count: i32,
    current_reorg_depth: i32,
    max_reorg_depth: i32,
}
