specVersion: 0.0.2
description: Serum for Solana
repository: https://github.com/massbitprotocol/massbitprotocol/tree/main/user-example
schema:
  file: ./schema.graphql
dataSources:
  - kind: solana
    name: index-serum
    network: mainnet
    source:
      address: '0xf73D010412Fb5835C310728F0Ba1b7DFDe88379A'
      abi: SolanaSerum
    mapping:
      kind: solana/BlockHandler
      apiVersion: 0.0.4
      language: rust
      entities:
        - SolanaSerum
      blockHandlers:
        - handler: handleBlock
      file: ./src/mapping.rs
      abis:
        - name: SolanaSerum
          file: ./abis/SolanaSerum.json